### ISSUE TITLE
VMware process running as different use is not patched

### ISSUE THREAD

**Issue by conioh** [sysprogs/VirtualKD#1]
Running `vmware.exe` as a different user than the one running `vmmon64.exe` does not work, even though both process are running in the **same Terminal Services session**.
The _Pipe name_ column keeps saying "loading..." and the log is empty.

The usage scenario is not running VMware Workstation intentionally as a different user, but rather running VMware under a standard (non-administrator) account, while running `vmmon64.exe` as a different account, since it requires elevation.

![1](https://cloud.githubusercontent.com/assets/10606081/14683819/75c1a784-0735-11e6-96ca-166a1e1ac063.PNG)

**Comment by sysprogs** [comment]
Thanks for reporting this. We don't regularly maintain VirtualKD anymore, so we will not provide a fix for it. If anyone is willing to submit a pull request resolving this, we will gladly merge it in.
